openapi: 3.0.1
info:
  title: Jobs API
  description: ''
  version: 1.0.0
tags:
  - name: Auth
  - name: Jobs
paths:
  /auth/register:
    post:
      summary: Register User
      deprecated: false
      description: ''
      tags:
        - Auth
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
                - password
            example:
              name: habeeb
              email: habeeb@gmail.com
              password: secret
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /auth/login:
    post:
      summary: Login user
      deprecated: false
      description: ''
      tags:
        - Auth
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
            example:
              email: anna@gmail.com
              password: secret
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /jobs:
    post:
      summary: Create job
      deprecated: false
      description: ''
      tags:
        - Jobs
      parameters:
        - name: Authorization
          in: header
          description: ''
          required: false
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGQyMDIxZmMzMTM3ZmI4YTQ0ZWEwNGEiLCJuYW1lIjoiYW5uYSIsImlhdCI6MTc1ODU5MzU2NywiZXhwIjoxNzYxMTg1NTY3fQ.VbYTXReiVr-TNBQUijVCP7KN1qUdylgVgYteJo53y1Y
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                company:
                  type: string
                position:
                  type: string
              required:
                - company
                - position
            example:
              company: netflix
              position: junior dev
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
    get:
      summary: Get All Jobs
      deprecated: false
      description: ''
      tags:
        - Jobs
      parameters:
        - name: Authorization
          in: header
          description: ''
          required: false
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGQyMDIxZmMzMTM3ZmI4YTQ0ZWEwNGEiLCJuYW1lIjoiYW5uYSIsImlhdCI6MTc1ODcwMzEzOCwiZXhwIjoxNzYxMjk1MTM4fQ.8-VoFo0r0J5A88p9xG9LThhKdzC8ajix6KG8uCWeka4
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /jobs/{id}:
    parameters:
    - in: path
      name: id
      schema:
        type: string
      required: true
      description: The job ID
    get:
      summary: Get Single Job
      deprecated: false
      description: ''
      tags:
        - Jobs
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
    patch:
      summary: Update job
      deprecated: false
      description: ''
      tags:
        - Jobs
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                company:
                  type: string
                position:
                  type: string
              required:
                - company
                - position
            example:
              company: random
              position: senior full stack dev
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
    delete:
      summary: Delete job
      deprecated: false
      description: ''
      tags:
        - Jobs
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
servers:
  - url: https://jobs-api-taupe.vercel.app/api/v1
    description: Production
security:
  - bearer: []
